# To create this environment, run this line in the terimnal:
# conda env create -f environment.yml
#
# Note: For GPU support, install PyTorch separately first (from https://pytorch.org/ for your device)
# 
# Then activate the environment 
# conda activate nanogpt
#
# or install the dependencies with pip separately:
# pip install torch tiktoken transformers datasets wandb ipykernel


name: nanogpt
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - tqdm
  - pip:
    - torch
    - tiktoken
    - transformers
    - datasets
    - wandb
    - ipykernel